In [13]:
#Simple 2 layer Neural Network to predict output of a XOR logic gate
#An Exclusive Or f(ie. XOR) unction returns a 1 only if all the inputs are either 0 or 1
#https://www.dummies.com/programming/python/how-to-build-a-simple-neural-network-in-python/

# 2 Layer Neural Network in NumPy
import numpy as np

# X = input of our 3 input XOR gate
# set up the inputs of the neural network (right from the table)
X = np.array(([0,0,0],[0,0,1],[0,1,0], \
[0,1,1],[1,0,0],[1,0,1],[1,1,0],[1,1,1]), dtype=float)

# y = our output of our neural network
y = np.array(([1], [0], [0], [0], [0], \
[0], [0], [1]), dtype=float)

# what value we want to predict
xPredicted = np.array(([0,0,1]), dtype=float)
X = X/np.amax(X, axis=0) # maximum of X input array

# maximum of xPredicted (our input data for the prediction)
xPredicted = xPredicted/np.amax(xPredicted, axis=0)

# set up our Loss file for graphing
lossFile = open("SumSquaredLossList.csv", "w")
class Neural_Network (object):
    def __init__(self): #parameters
        self.inputLayerSize = 3 # X1,X2,X3
        self.outputLayerSize = 1 # Y1
        self.hiddenLayerSize = 4 # Size of the hidden layer
        # build weights of each layer
        # set to random values
        # look at the interconnection diagram to make sense of this
        # 3x4 matrix for input to hidden
        self.W1 = \
        np.random.randn(self.inputLayerSize, self.hiddenLayerSize)
        
        # 4x1 matrix for hidden layer to output
        self.W2 = \
        np.random.randn(self.hiddenLayerSize, self.outputLayerSize)
        
    def feedForward(self, X):
        # feedForward propagation through our network
        # dot product of X (input) and first set of 3x4 weights
        self.z = np.dot(X, self.W1)
        # the activationSigmoid activation function - neural magic
        self.z2 = self.activationSigmoid(self.z)
        # dot product of hidden layer (z2) and second set of 4x1 weights
        self.z3 = np.dot(self.z2, self.W2)
        # final activation function - more neural magic
        o = self.activationSigmoid(self.z3)
        return o
    
    def backwardPropagate(self, X, y, o):
        # backward propagate through the network
        # calculate the error in output
        self.o_error = y - o
        # apply derivative of activationSigmoid to error
        self.o_delta = self.o_error*self.activationSigmoidPrime(o)
        # z2 error: how much our hidden layer weights contributed to output
        # error
        self.z2_error = self.o_delta.dot(self.W2.T)
        # applying derivative of activationSigmoid to z2 error
        self.z2_delta = self.z2_error*self.activationSigmoidPrime(self.z2)
        # adjusting first set (inputLayer --> hiddenLayer) weights
        self.W1 += X.T.dot(self.z2_delta)
        # adjusting second set (hiddenLayer --> outputLayer) weights
        self.W2 += self.z2.T.dot(self.o_delta)
        
    def trainNetwork(self, X, y):
        # feed forward the loop
        o = self.feedForward(X)
        # and then back propagate the values (feedback)
        self.backwardPropagate(X, y, o)

    def activationSigmoid(self, s):
        # activation function
        # simple activationSigmoid curve as in the book
        return 1/(1+np.exp(-s))

    def activationSigmoidPrime(self, s):
        # First derivative of activationSigmoid
        # calculus time!
        return s * (1 - s)

    def saveSumSquaredLossList(self,i,error):
        lossFile.write(str(i)+","+str(error.tolist())+'\n')

    def saveWeights(self):
        # save this in order to reproduce our cool network
        np.savetxt("weightsLayer1.txt", self.W1, fmt="%s")
        np.savetxt("weightsLayer2.txt", self.W2, fmt="%s")

    def predictOutput(self):
        print ("Predicted XOR output data based on trained weights: ")
        print ("Expected (X1-X3): \n" + str(xPredicted))
        print ("Output (Y1): \n" + str(self.feedForward(xPredicted)))
        
myNeuralNetwork = Neural_Network()
trainingEpochs = 1000

#trainingEpochs = 100000
for i in range(trainingEpochs): # train myNeuralNetwork 1,000 times
    print ("Epoch # " + str(i) + "\n")
    print ("Network Input : \n" + str(X))
    print ("Expected Output of XOR Gate Neural Network: \n" + str(y))
    print ("Actual Output from XOR Gate Neural Network: \n" + \
           str(myNeuralNetwork.feedForward(X)))
    
    # mean sum squared loss
    Loss = np.mean(np.square(y - myNeuralNetwork.feedForward(X)))
    myNeuralNetwork.saveSumSquaredLossList(i,Loss)
    print ("Sum Squared Loss: \n" + str(Loss))
    print ("\n")
    myNeuralNetwork.trainNetwork(X, y)
    myNeuralNetwork.saveWeights()
    myNeuralNetwork.predictOutput()

Epoch # 0

Network Input : 
[[0. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 1.]
 [1. 0. 0.]
 [1. 0. 1.]
 [1. 1. 0.]
 [1. 1. 1.]]
Expected Output of XOR Gate Neural Network: 
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]]
Actual Output from XOR Gate Neural Network: 
[[0.13573953]
 [0.14145351]
 [0.22333146]
 [0.21476495]
 [0.13920037]
 [0.14686039]
 [0.23989462]
 [0.23911498]]
Sum Squared Loss: 
0.1925495416669999


Predicted XOR output data based on trained weights: 
Expected (X1-X3): 
[0. 0. 1.]
Output (Y1): 
[0.15238359]
Epoch # 1

Network Input : 
[[0. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 1.]
 [1. 0. 0.]
 [1. 0. 1.]
 [1. 1. 0.]
 [1. 1. 1.]]
Expected Output of XOR Gate Neural Network: 
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]]
Actual Output from XOR Gate Neural Network: 
[[0.1443436 ]
 [0.15238359]
 [0.23539015]
 [0.2294049 ]
 [0.15179849]
 [0.16175214]
 [0.25766483]
 [0.25941684]]
Sum Squared Loss: 
0.19093311010668876


Predicted XOR output data based on trained weights: 
Ex

Predicted XOR output data based on trained weights: 
Expected (X1-X3): 
[0. 0. 1.]
Output (Y1): 
[0.20746456]
Epoch # 29

Network Input : 
[[0. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 1.]
 [1. 0. 0.]
 [1. 0. 1.]
 [1. 1. 0.]
 [1. 1. 1.]]
Expected Output of XOR Gate Neural Network: 
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]]
Actual Output from XOR Gate Neural Network: 
[[0.18363995]
 [0.20746456]
 [0.24091572]
 [0.25452056]
 [0.21213738]
 [0.23439513]
 [0.29402168]
 [0.31742979]]
Sum Squared Loss: 
0.1855750718071041


Predicted XOR output data based on trained weights: 
Expected (X1-X3): 
[0. 0. 1.]
Output (Y1): 
[0.20810135]
Epoch # 30

Network Input : 
[[0. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 1.]
 [1. 0. 0.]
 [1. 0. 1.]
 [1. 1. 0.]
 [1. 1. 1.]]
Expected Output of XOR Gate Neural Network: 
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]]
Actual Output from XOR Gate Neural Network: 
[[0.1839199 ]
 [0.20810135]
 [0.24024812]
 [0.25421621]
 [0.21257513]
 [0.23502713]
 [0.2936968 ]

Predicted XOR output data based on trained weights: 
Expected (X1-X3): 
[0. 0. 1.]
Output (Y1): 
[0.21904345]
Epoch # 53

Network Input : 
[[0. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 1.]
 [1. 0. 0.]
 [1. 0. 1.]
 [1. 1. 0.]
 [1. 1. 1.]]
Expected Output of XOR Gate Neural Network: 
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]]
Actual Output from XOR Gate Neural Network: 
[[0.18640343]
 [0.21904345]
 [0.22903796]
 [0.25014966]
 [0.21677574]
 [0.24328426]
 [0.28931761]
 [0.32415871]]
Sum Squared Loss: 
0.18394971564719548


Predicted XOR output data based on trained weights: 
Expected (X1-X3): 
[0. 0. 1.]
Output (Y1): 
[0.21939814]
Epoch # 54

Network Input : 
[[0. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 1.]
 [1. 0. 0.]
 [1. 0. 1.]
 [1. 1. 0.]
 [1. 1. 1.]]
Expected Output of XOR Gate Neural Network: 
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]]
Actual Output from XOR Gate Neural Network: 
[[0.1863745 ]
 [0.21939814]
 [0.22866553]
 [0.25004975]
 [0.21677121]
 [0.24343919]
 [0.28924603

Predicted XOR output data based on trained weights: 
Expected (X1-X3): 
[0. 0. 1.]
Output (Y1): 
[0.22726632]
Epoch # 83

Network Input : 
[[0. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 1.]
 [1. 0. 0.]
 [1. 0. 1.]
 [1. 1. 0.]
 [1. 1. 1.]]
Expected Output of XOR Gate Neural Network: 
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]]
Actual Output from XOR Gate Neural Network: 
[[0.18209044]
 [0.22726632]
 [0.21875562]
 [0.24739169]
 [0.21283773]
 [0.24358985]
 [0.29026331]
 [0.34067016]]
Sum Squared Loss: 
0.18166090489916514


Predicted XOR output data based on trained weights: 
Expected (X1-X3): 
[0. 0. 1.]
Output (Y1): 
[0.22747933]
Epoch # 84

Network Input : 
[[0. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 1.]
 [1. 0. 0.]
 [1. 0. 1.]
 [1. 1. 0.]
 [1. 1. 1.]]
Expected Output of XOR Gate Neural Network: 
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]]
Actual Output from XOR Gate Neural Network: 
[[0.1818403 ]
 [0.22747933]
 [0.21840358]
 [0.2472771 ]
 [0.21260163]
 [0.24347611]
 [0.29038275

Predicted XOR output data based on trained weights: 
Expected (X1-X3): 
[0. 0. 1.]
Output (Y1): 
[0.23249631]
Epoch # 111

Network Input : 
[[0. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 1.]
 [1. 0. 0.]
 [1. 0. 1.]
 [1. 1. 0.]
 [1. 1. 1.]]
Expected Output of XOR Gate Neural Network: 
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]]
Actual Output from XOR Gate Neural Network: 
[[0.17299713]
 [0.23249631]
 [0.2074815 ]
 [0.24269554]
 [0.20447271]
 [0.23807902]
 [0.29473997]
 [0.36437865]]
Sum Squared Loss: 
0.1786643556444579


Predicted XOR output data based on trained weights: 
Expected (X1-X3): 
[0. 0. 1.]
Output (Y1): 
[0.2326628]
Epoch # 112

Network Input : 
[[0. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 1.]
 [1. 0. 0.]
 [1. 0. 1.]
 [1. 1. 0.]
 [1. 1. 1.]]
Expected Output of XOR Gate Neural Network: 
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]]
Actual Output from XOR Gate Neural Network: 
[[0.17259992]
 [0.2326628 ]
 [0.20701339]
 [0.24245986]
 [0.20411607]
 [0.23779834]
 [0.29492381

Predicted XOR output data based on trained weights: 
Expected (X1-X3): 
[0. 0. 1.]
Output (Y1): 
[0.23535273]
Epoch # 129

Network Input : 
[[0. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 1.]
 [1. 0. 0.]
 [1. 0. 1.]
 [1. 1. 0.]
 [1. 1. 1.]]
Expected Output of XOR Gate Neural Network: 
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]]
Actual Output from XOR Gate Neural Network: 
[[0.16523379]
 [0.23535273]
 [0.19829874]
 [0.23760626]
 [0.19760489]
 [0.23221355]
 [0.29794447]
 [0.38365374]]
Sum Squared Loss: 
0.17620363819038176


Predicted XOR output data based on trained weights: 
Expected (X1-X3): 
[0. 0. 1.]
Output (Y1): 
[0.23550295]
Epoch # 130

Network Input : 
[[0. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 1.]
 [1. 0. 0.]
 [1. 0. 1.]
 [1. 1. 0.]
 [1. 1. 1.]]
Expected Output of XOR Gate Neural Network: 
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]]
Actual Output from XOR Gate Neural Network: 
[[0.16476879]
 [0.23550295]
 [0.19774323]
 [0.2372693 ]
 [0.19720003]
 [0.23183913]
 [0.298106

Predicted XOR output data based on trained weights: 
Expected (X1-X3): 
[0. 0. 1.]
Output (Y1): 
[0.23826202]
Epoch # 150

Network Input : 
[[0. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 1.]
 [1. 0. 0.]
 [1. 0. 1.]
 [1. 1. 0.]
 [1. 1. 1.]]
Expected Output of XOR Gate Neural Network: 
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]]
Actual Output from XOR Gate Neural Network: 
[[0.15496202]
 [0.23826202]
 [0.18582358]
 [0.2293209 ]
 [0.18883941]
 [0.22339945]
 [0.30059119]
 [0.40951141]]
Sum Squared Loss: 
0.17282199123735814


Predicted XOR output data based on trained weights: 
Expected (X1-X3): 
[0. 0. 1.]
Output (Y1): 
[0.23838367]
Epoch # 151

Network Input : 
[[0. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 1.]
 [1. 0. 0.]
 [1. 0. 1.]
 [1. 1. 0.]
 [1. 1. 1.]]
Expected Output of XOR Gate Neural Network: 
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]]
Actual Output from XOR Gate Neural Network: 
[[0.15445365]
 [0.23838367]
 [0.18519557]
 [0.22886475]
 [0.18841628]
 [0.22293433]
 [0.300665

Predicted XOR output data based on trained weights: 
Expected (X1-X3): 
[0. 0. 1.]
Output (Y1): 
[0.24027458]
Epoch # 172

Network Input : 
[[0. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 1.]
 [1. 0. 0.]
 [1. 0. 1.]
 [1. 1. 0.]
 [1. 1. 1.]]
Expected Output of XOR Gate Neural Network: 
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]]
Actual Output from XOR Gate Neural Network: 
[[0.14368402]
 [0.24027458]
 [0.17174007]
 [0.21814576]
 [0.17978101]
 [0.21244304]
 [0.3007294 ]
 [0.43973362]]
Sum Squared Loss: 
0.1687351245290325


Predicted XOR output data based on trained weights: 
Expected (X1-X3): 
[0. 0. 1.]
Output (Y1): 
[0.24032118]
Epoch # 173

Network Input : 
[[0. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 1.]
 [1. 0. 0.]
 [1. 0. 1.]
 [1. 1. 0.]
 [1. 1. 1.]]
Expected Output of XOR Gate Neural Network: 
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]]
Actual Output from XOR Gate Neural Network: 
[[0.14317398]
 [0.24032118]
 [0.17109905]
 [0.21758668]
 [0.17939129]
 [0.21191564]
 [0.3006519

Predicted XOR output data based on trained weights: 
Expected (X1-X3): 
[0. 0. 1.]
Output (Y1): 
[0.23953577]
Epoch # 196

Network Input : 
[[0. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 1.]
 [1. 0. 0.]
 [1. 0. 1.]
 [1. 1. 0.]
 [1. 1. 1.]]
Expected Output of XOR Gate Neural Network: 
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]]
Actual Output from XOR Gate Neural Network: 
[[0.1318057 ]
 [0.23953577]
 [0.15692937]
 [0.20382631]
 [0.17139339]
 [0.19943486]
 [0.29652316]
 [0.47591178]]
Sum Squared Loss: 
0.1636318903026454


Predicted XOR output data based on trained weights: 
Expected (X1-X3): 
[0. 0. 1.]
Output (Y1): 
[0.23939934]
Epoch # 197

Network Input : 
[[0. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 1.]
 [1. 0. 0.]
 [1. 0. 1.]
 [1. 1. 0.]
 [1. 1. 1.]]
Expected Output of XOR Gate Neural Network: 
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]]
Actual Output from XOR Gate Neural Network: 
[[0.1313325 ]
 [0.23939934]
 [0.15635036]
 [0.20319691]
 [0.17109605]
 [0.19888556]
 [0.2962362

Predicted XOR output data based on trained weights: 
Expected (X1-X3): 
[0. 0. 1.]
Output (Y1): 
[0.23171661]
Epoch # 223

Network Input : 
[[0. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 1.]
 [1. 0. 0.]
 [1. 0. 1.]
 [1. 1. 0.]
 [1. 1. 1.]]
Expected Output of XOR Gate Neural Network: 
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]]
Actual Output from XOR Gate Neural Network: 
[[0.11985195]
 [0.23171661]
 [0.14288725]
 [0.18637267]
 [0.1651266 ]
 [0.18489373]
 [0.28547544]
 [0.52077312]]
Sum Squared Loss: 
0.1570139795635498


Predicted XOR output data based on trained weights: 
Expected (X1-X3): 
[0. 0. 1.]
Output (Y1): 
[0.23124684]
Epoch # 224

Network Input : 
[[0. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 1.]
 [1. 0. 0.]
 [1. 0. 1.]
 [1. 1. 0.]
 [1. 1. 1.]]
Expected Output of XOR Gate Neural Network: 
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]]
Actual Output from XOR Gate Neural Network: 
[[0.11944474]
 [0.23124684]
 [0.14243681]
 [0.18571678]
 [0.16496554]
 [0.18437617]
 [0.2849351

Predicted XOR output data based on trained weights: 
Expected (X1-X3): 
[0. 0. 1.]
Output (Y1): 
[0.21847281]
Epoch # 245

Network Input : 
[[0. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 1.]
 [1. 0. 0.]
 [1. 0. 1.]
 [1. 1. 0.]
 [1. 1. 1.]]
Expected Output of XOR Gate Neural Network: 
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]]
Actual Output from XOR Gate Neural Network: 
[[0.11154131]
 [0.21847281]
 [0.13419512]
 [0.17202797]
 [0.16261885]
 [0.17407729]
 [0.27161269]
 [0.56000009]]
Sum Squared Loss: 
0.1511015404663265


Predicted XOR output data based on trained weights: 
Expected (X1-X3): 
[0. 0. 1.]
Output (Y1): 
[0.2177414]
Epoch # 246

Network Input : 
[[0. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 1.]
 [1. 0. 0.]
 [1. 0. 1.]
 [1. 1. 0.]
 [1. 1. 1.]]
Expected Output of XOR Gate Neural Network: 
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]]
Actual Output from XOR Gate Neural Network: 
[[0.11119716]
 [0.2177414 ]
 [0.13386025]
 [0.17138507]
 [0.1625503 ]
 [0.17361719]
 [0.27089337

Predicted XOR output data based on trained weights: 
Expected (X1-X3): 
[0. 0. 1.]
Output (Y1): 
[0.20585271]
Epoch # 261

Network Input : 
[[0. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 1.]
 [1. 0. 0.]
 [1. 0. 1.]
 [1. 1. 0.]
 [1. 1. 1.]]
Expected Output of XOR Gate Neural Network: 
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]]
Actual Output from XOR Gate Neural Network: 
[[0.10641391]
 [0.20585271]
 [0.12945086]
 [0.16191979]
 [0.16186779]
 [0.16707573]
 [0.25940829]
 [0.5887475 ]]
Sum Squared Loss: 
0.14679796688023708


Predicted XOR output data based on trained weights: 
Expected (X1-X3): 
[0. 0. 1.]
Output (Y1): 
[0.20501507]
Epoch # 262

Network Input : 
[[0. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 1.]
 [1. 0. 0.]
 [1. 0. 1.]
 [1. 1. 0.]
 [1. 1. 1.]]
Expected Output of XOR Gate Neural Network: 
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]]
Actual Output from XOR Gate Neural Network: 
[[0.10612129]
 [0.20501507]
 [0.1291974 ]
 [0.16130296]
 [0.1618415 ]
 [0.16666383]
 [0.258605

 [0.62453476]]
Sum Squared Loss: 
0.14156429475530427


Predicted XOR output data based on trained weights: 
Expected (X1-X3): 
[0. 0. 1.]
Output (Y1): 
[0.18713326]
Epoch # 283

Network Input : 
[[0. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 1.]
 [1. 0. 0.]
 [1. 0. 1.]
 [1. 1. 0.]
 [1. 1. 1.]]
Expected Output of XOR Gate Neural Network: 
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]]
Actual Output from XOR Gate Neural Network: 
[[0.10079835]
 [0.18713326]
 [0.12503043]
 [0.14888694]
 [0.16164685]
 [0.15869834]
 [0.24124013]
 [0.62614778]]
Sum Squared Loss: 
0.14133244154695956


Predicted XOR output data based on trained weights: 
Expected (X1-X3): 
[0. 0. 1.]
Output (Y1): 
[0.18629446]
Epoch # 284

Network Input : 
[[0. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 1.]
 [1. 0. 0.]
 [1. 0. 1.]
 [1. 1. 0.]
 [1. 1. 1.]]
Expected Output of XOR Gate Neural Network: 
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]]
Actual Output from XOR Gate Neural Network: 
[[0.10058581]
 [0.18629446]
 [0.124886

Predicted XOR output data based on trained weights: 
Expected (X1-X3): 
[0. 0. 1.]
Output (Y1): 
[0.16613573]
Epoch # 310

Network Input : 
[[0. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 1.]
 [1. 0. 0.]
 [1. 0. 1.]
 [1. 1. 0.]
 [1. 1. 1.]]
Expected Output of XOR Gate Neural Network: 
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]]
Actual Output from XOR Gate Neural Network: 
[[0.0964571 ]
 [0.16613573]
 [0.12289893]
 [0.13475127]
 [0.16205475]
 [0.15029926]
 [0.21940801]
 [0.66564213]]
Sum Squared Loss: 
0.1357549469754152


Predicted XOR output data based on trained weights: 
Expected (X1-X3): 
[0. 0. 1.]
Output (Y1): 
[0.16543937]
Epoch # 311

Network Input : 
[[0. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 1.]
 [1. 0. 0.]
 [1. 0. 1.]
 [1. 1. 0.]
 [1. 1. 1.]]
Expected Output of XOR Gate Neural Network: 
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]]
Actual Output from XOR Gate Neural Network: 
[[0.09635336]
 [0.16543937]
 [0.12288855]
 [0.13427094]
 [0.16208259]
 [0.15002735]
 [0.2186406

Actual Output from XOR Gate Neural Network: 
[[0.0951155 ]
 [0.15068897]
 [0.12401992]
 [0.12365283]
 [0.16310392]
 [0.14437381]
 [0.20145319]
 [0.6948557 ]]
Sum Squared Loss: 
0.13166715155111425


Predicted XOR output data based on trained weights: 
Expected (X1-X3): 
[0. 0. 1.]
Output (Y1): 
[0.15015414]
Epoch # 336

Network Input : 
[[0. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 1.]
 [1. 0. 0.]
 [1. 0. 1.]
 [1. 1. 0.]
 [1. 1. 1.]]
Expected Output of XOR Gate Neural Network: 
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]]
Actual Output from XOR Gate Neural Network: 
[[0.09511638]
 [0.15015414]
 [0.12412157]
 [0.12324681]
 [0.1631633 ]
 [0.14417586]
 [0.20079164]
 [0.69588253]]
Sum Squared Loss: 
0.13152128016329562


Predicted XOR output data based on trained weights: 
Expected (X1-X3): 
[0. 0. 1.]
Output (Y1): 
[0.14962536]
Epoch # 337

Network Input : 
[[0. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 1.]
 [1. 0. 0.]
 [1. 0. 1.]
 [1. 1. 0.]
 [1. 1. 1.]]
Expected Output of XOR Gate Neural

 [1. 1. 1.]]
Expected Output of XOR Gate Neural Network: 
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]]
Actual Output from XOR Gate Neural Network: 
[[0.09641212]
 [0.13900043]
 [0.12768832]
 [0.11428102]
 [0.16507135]
 [0.14040205]
 [0.18629837]
 [0.71756363]]
Sum Squared Loss: 
0.1283244138132249


Predicted XOR output data based on trained weights: 
Expected (X1-X3): 
[0. 0. 1.]
Output (Y1): 
[0.13859898]
Epoch # 361

Network Input : 
[[0. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 1.]
 [1. 0. 0.]
 [1. 0. 1.]
 [1. 1. 0.]
 [1. 1. 1.]]
Expected Output of XOR Gate Neural Network: 
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]]
Actual Output from XOR Gate Neural Network: 
[[0.09651981]
 [0.13859898]
 [0.12787903]
 [0.11393748]
 [0.16517217]
 [0.14028741]
 [0.18575298]
 [0.71835077]]
Sum Squared Loss: 
0.12820172344574374


Predicted XOR output data based on trained weights: 
Expected (X1-X3): 
[0. 0. 1.]
Output (Y1): 
[0.13820202]
Epoch # 362

Network Input : 
[[0. 0. 0.]
 [0. 0. 1.]
 

Actual Output from XOR Gate Neural Network: 
[[0.10022766]
 [0.13047371]
 [0.13297487]
 [0.10660344]
 [0.16798645]
 [0.13867619]
 [0.17453914]
 [0.73416295]]
Sum Squared Loss: 
0.12553050519113162


Predicted XOR output data based on trained weights: 
Expected (X1-X3): 
[0. 0. 1.]
Output (Y1): 
[0.1301623]
Epoch # 385

Network Input : 
[[0. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 1.]
 [1. 0. 0.]
 [1. 0. 1.]
 [1. 1. 0.]
 [1. 1. 1.]]
Expected Output of XOR Gate Neural Network: 
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]]
Actual Output from XOR Gate Neural Network: 
[[0.10044401]
 [0.1301623 ]
 [0.13322203]
 [0.10630726]
 [0.16813049]
 [0.13865276]
 [0.1741106 ]
 [0.73475629]]
Sum Squared Loss: 
0.12541921455404623


Predicted XOR output data based on trained weights: 
Expected (X1-X3): 
[0. 0. 1.]
Output (Y1): 
[0.12985387]
Epoch # 386

Network Input : 
[[0. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 1.]
 [1. 0. 0.]
 [1. 0. 1.]
 [1. 1. 0.]
 [1. 1. 1.]]
Expected Output of XOR Gate Neural 

Expected Output of XOR Gate Neural Network: 
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]]
Actual Output from XOR Gate Neural Network: 
[[0.10487253]
 [0.12528145]
 [0.13764255]
 [0.10152563]
 [0.17085303]
 [0.13889204]
 [0.16761041]
 [0.74374244]]
Sum Squared Loss: 
0.12355556218868216


Predicted XOR output data based on trained weights: 
Expected (X1-X3): 
[0. 0. 1.]
Output (Y1): 
[0.12501573]
Epoch # 403

Network Input : 
[[0. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 1.]
 [1. 0. 0.]
 [1. 0. 1.]
 [1. 1. 0.]
 [1. 1. 1.]]
Expected Output of XOR Gate Neural Network: 
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]]
Actual Output from XOR Gate Neural Network: 
[[0.10517886]
 [0.12501573]
 [0.13791264]
 [0.10125842]
 [0.17102909]
 [0.13894476]
 [0.1672753 ]
 [0.74420861]]
Sum Squared Loss: 
0.12344672867541057


Predicted XOR output data based on trained weights: 
Expected (X1-X3): 
[0. 0. 1.]
Output (Y1): 
[0.12475208]
Epoch # 404

Network Input : 
[[0. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 

Predicted XOR output data based on trained weights: 
Expected (X1-X3): 
[0. 0. 1.]
Output (Y1): 
[0.11985196]
Epoch # 424

Network Input : 
[[0. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 1.]
 [1. 0. 0.]
 [1. 0. 1.]
 [1. 1. 0.]
 [1. 1. 1.]]
Expected Output of XOR Gate Neural Network: 
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]]
Actual Output from XOR Gate Neural Network: 
[[0.11289602]
 [0.11985196]
 [0.14370896]
 [0.09596853]
 [0.1751177 ]
 [0.14109745]
 [0.16151321]
 [0.75250043]]
Sum Squared Loss: 
0.12113718033347991


Predicted XOR output data based on trained weights: 
Expected (X1-X3): 
[0. 0. 1.]
Output (Y1): 
[0.11962275]
Epoch # 425

Network Input : 
[[0. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 1.]
 [1. 0. 0.]
 [1. 0. 1.]
 [1. 1. 0.]
 [1. 1. 1.]]
Expected Output of XOR Gate Neural Network: 
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]]
Actual Output from XOR Gate Neural Network: 
[[0.11332817]
 [0.11962275]
 [0.14398752]
 [0.09573092]
 [0.17533027]
 [0.14125097]
 [0.161301

 [1. 1. 1.]]
Expected Output of XOR Gate Neural Network: 
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]]
Actual Output from XOR Gate Neural Network: 
[[0.12449089]
 [0.1148517 ]
 [0.15004486]
 [0.09078521]
 [0.18036086]
 [0.14583115]
 [0.15815828]
 [0.75852242]]
Sum Squared Loss: 
0.11844809471528958


Predicted XOR output data based on trained weights: 
Expected (X1-X3): 
[0. 0. 1.]
Output (Y1): 
[0.11464502]
Epoch # 448

Network Input : 
[[0. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 1.]
 [1. 0. 0.]
 [1. 0. 1.]
 [1. 1. 0.]
 [1. 1. 1.]]
Expected Output of XOR Gate Neural Network: 
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]]
Actual Output from XOR Gate Neural Network: 
[[0.1250777 ]
 [0.11464502]
 [0.15031407]
 [0.09057188]
 [0.18060334]
 [0.14609389]
 [0.158086  ]
 [0.75871675]]
Sum Squared Loss: 
0.11832498404870168


Predicted XOR output data based on trained weights: 
Expected (X1-X3): 
[0. 0. 1.]
Output (Y1): 
[0.11443906]
Epoch # 449

Network Input : 
[[0. 0. 0.]
 [0. 0. 1.]


Predicted XOR output data based on trained weights: 
Expected (X1-X3): 
[0. 0. 1.]
Output (Y1): 
[0.10814954]
Epoch # 481

Network Input : 
[[0. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 1.]
 [1. 0. 0.]
 [1. 0. 1.]
 [1. 1. 0.]
 [1. 1. 1.]]
Expected Output of XOR Gate Neural Network: 
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]]
Actual Output from XOR Gate Neural Network: 
[[0.14866335]
 [0.10814954]
 [0.15856542]
 [0.08389179]
 [0.18882872]
 [0.1572196 ]
 [0.15922676]
 [0.76235973]]
Sum Squared Loss: 
0.11385644890993604


Predicted XOR output data based on trained weights: 
Expected (X1-X3): 
[0. 0. 1.]
Output (Y1): 
[0.10796064]
Epoch # 482

Network Input : 
[[0. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 1.]
 [1. 0. 0.]
 [1. 0. 1.]
 [1. 1. 0.]
 [1. 1. 1.]]
Expected Output of XOR Gate Neural Network: 
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]]
Actual Output from XOR Gate Neural Network: 
[[0.14950766]
 [0.10796064]
 [0.15878913]
 [0.08369538]
 [0.18907194]
 [0.15762256]
 [0.159366

Predicted XOR output data based on trained weights: 
Expected (X1-X3): 
[0. 0. 1.]
Output (Y1): 
[0.10445121]
Epoch # 501

Network Input : 
[[0. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 1.]
 [1. 0. 0.]
 [1. 0. 1.]
 [1. 1. 0.]
 [1. 1. 1.]]
Expected Output of XOR Gate Neural Network: 
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]]
Actual Output from XOR Gate Neural Network: 
[[0.16689459]
 [0.10445121]
 [0.16259798]
 [0.07993313]
 [0.19334535]
 [0.16577642]
 [0.16309674]
 [0.76250975]]
Sum Squared Loss: 
0.11070856290747315


Predicted XOR output data based on trained weights: 
Expected (X1-X3): 
[0. 0. 1.]
Output (Y1): 
[0.10427106]
Epoch # 502

Network Input : 
[[0. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 1.]
 [1. 0. 0.]
 [1. 0. 1.]
 [1. 1. 0.]
 [1. 1. 1.]]
Expected Output of XOR Gate Neural Network: 
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]]
Actual Output from XOR Gate Neural Network: 
[[0.16787496]
 [0.10427106]
 [0.16277158]
 [0.07973135]
 [0.19354532]
 [0.16622476]
 [0.163345

Actual Output from XOR Gate Neural Network: 
[[0.18852996]
 [0.1008003 ]
 [0.16552595]
 [0.07553859]
 [0.19677086]
 [0.17526316]
 [0.16921671]
 [0.76194399]]
Sum Squared Loss: 
0.10706126956574424


Predicted XOR output data based on trained weights: 
Expected (X1-X3): 
[0. 0. 1.]
Output (Y1): 
[0.10063505]
Epoch # 523

Network Input : 
[[0. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 1.]
 [1. 0. 0.]
 [1. 0. 1.]
 [1. 1. 0.]
 [1. 1. 1.]]
Expected Output of XOR Gate Neural Network: 
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]]
Actual Output from XOR Gate Neural Network: 
[[0.18960394]
 [0.10063505]
 [0.16562363]
 [0.07531944]
 [0.19688784]
 [0.17570851]
 [0.16954807]
 [0.76191638]]
Sum Squared Loss: 
0.10688025804117807


Predicted XOR output data based on trained weights: 
Expected (X1-X3): 
[0. 0. 1.]
Output (Y1): 
[0.1004708]
Epoch # 524

Network Input : 
[[0. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 1.]
 [1. 0. 0.]
 [1. 0. 1.]
 [1. 1. 0.]
 [1. 1. 1.]]
Expected Output of XOR Gate Neural 

Predicted XOR output data based on trained weights: 
Expected (X1-X3): 
[0. 0. 1.]
Output (Y1): 
[0.09619161]
Epoch # 554

Network Input : 
[[0. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 1.]
 [1. 0. 0.]
 [1. 0. 1.]
 [1. 1. 0.]
 [1. 1. 1.]]
Expected Output of XOR Gate Neural Network: 
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]]
Actual Output from XOR Gate Neural Network: 
[[0.22351702]
 [0.09619161]
 [0.16639546]
 [0.06801198]
 [0.19814458]
 [0.18805515]
 [0.1808215 ]
 [0.76201764]]
Sum Squared Loss: 
0.10105621917942972


Predicted XOR output data based on trained weights: 
Expected (X1-X3): 
[0. 0. 1.]
Output (Y1): 
[0.09607785]
Epoch # 555

Network Input : 
[[0. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 1.]
 [1. 0. 0.]
 [1. 0. 1.]
 [1. 1. 0.]
 [1. 1. 1.]]
Expected Output of XOR Gate Neural Network: 
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]]
Actual Output from XOR Gate Neural Network: 
[[0.22460645]
 [0.09607785]
 [0.16634326]
 [0.06776102]
 [0.19811114]
 [0.18838459]
 [0.181203

Expected Output of XOR Gate Neural Network: 
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]]
Actual Output from XOR Gate Neural Network: 
[[0.24282905]
 [0.09454972]
 [0.164711  ]
 [0.06339713]
 [0.1969639 ]
 [0.19306784]
 [0.18772651]
 [0.76349506]]
Sum Squared Loss: 
0.09758027561032802


Predicted XOR output data based on trained weights: 
Expected (X1-X3): 
[0. 0. 1.]
Output (Y1): 
[0.0944866]
Epoch # 573

Network Input : 
[[0. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 1.]
 [1. 0. 0.]
 [1. 0. 1.]
 [1. 1. 0.]
 [1. 1. 1.]]
Expected Output of XOR Gate Neural Network: 
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]]
Actual Output from XOR Gate Neural Network: 
[[0.24388026]
 [0.0944866 ]
 [0.16457223]
 [0.06313621]
 [0.19686676]
 [0.19328485]
 [0.18811028]
 [0.76361397]]
Sum Squared Loss: 
0.09738679664499184


Predicted XOR output data based on trained weights: 
Expected (X1-X3): 
[0. 0. 1.]
Output (Y1): 
[0.09442678]
Epoch # 574

Network Input : 
[[0. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [

Predicted XOR output data based on trained weights: 
Expected (X1-X3): 
[0. 0. 1.]
Output (Y1): 
[0.0939751]
Epoch # 593

Network Input : 
[[0. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 1.]
 [1. 0. 0.]
 [1. 0. 1.]
 [1. 1. 0.]
 [1. 1. 1.]]
Expected Output of XOR Gate Neural Network: 
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]]
Actual Output from XOR Gate Neural Network: 
[[0.26436075]
 [0.0939751 ]
 [0.16088753]
 [0.05789095]
 [0.19444906]
 [0.19610325]
 [0.19575183]
 [0.76676799]]
Sum Squared Loss: 
0.09352693290812227


Predicted XOR output data based on trained weights: 
Expected (X1-X3): 
[0. 0. 1.]
Output (Y1): 
[0.09399021]
Epoch # 594

Network Input : 
[[0. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 1.]
 [1. 0. 0.]
 [1. 0. 1.]
 [1. 1. 0.]
 [1. 1. 1.]]
Expected Output of XOR Gate Neural Network: 
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]]
Actual Output from XOR Gate Neural Network: 
[[0.26535802]
 [0.09399021]
 [0.16066136]
 [0.05762924]
 [0.19431049]
 [0.1961651 ]
 [0.1961322

 [0.77330718]]
Sum Squared Loss: 
0.08801542367251718


Predicted XOR output data based on trained weights: 
Expected (X1-X3): 
[0. 0. 1.]
Output (Y1): 
[0.09629891]
Epoch # 623

Network Input : 
[[0. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 1.]
 [1. 0. 0.]
 [1. 0. 1.]
 [1. 1. 0.]
 [1. 1. 1.]]
Expected Output of XOR Gate Neural Network: 
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]]
Actual Output from XOR Gate Neural Network: 
[[0.29337183]
 [0.09629891]
 [0.15278543]
 [0.05019484]
 [0.19001067]
 [0.19461028]
 [0.20714973]
 [0.77355479]]
Sum Squared Loss: 
0.08782817727603272


Predicted XOR output data based on trained weights: 
Expected (X1-X3): 
[0. 0. 1.]
Output (Y1): 
[0.09644383]
Epoch # 624

Network Input : 
[[0. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 1.]
 [1. 0. 0.]
 [1. 0. 1.]
 [1. 1. 0.]
 [1. 1. 1.]]
Expected Output of XOR Gate Neural Network: 
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]]
Actual Output from XOR Gate Neural Network: 
[[0.2943127 ]
 [0.09644383]
 [0.152478

Predicted XOR output data based on trained weights: 
Expected (X1-X3): 
[0. 0. 1.]
Output (Y1): 
[0.0997475]
Epoch # 642

Network Input : 
[[0. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 1.]
 [1. 0. 0.]
 [1. 0. 1.]
 [1. 1. 0.]
 [1. 1. 1.]]
Expected Output of XOR Gate Neural Network: 
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]]
Actual Output from XOR Gate Neural Network: 
[[0.31107582]
 [0.0997475 ]
 [0.1467498 ]
 [0.04555879]
 [0.18714007]
 [0.19033305]
 [0.21436918]
 [0.7782517 ]]
Sum Squared Loss: 
0.08431896609534426


Predicted XOR output data based on trained weights: 
Expected (X1-X3): 
[0. 0. 1.]
Output (Y1): 
[0.09996706]
Epoch # 643

Network Input : 
[[0. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 1.]
 [1. 0. 0.]
 [1. 0. 1.]
 [1. 1. 0.]
 [1. 1. 1.]]
Expected Output of XOR Gate Neural Network: 
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]]
Actual Output from XOR Gate Neural Network: 
[[0.31200007]
 [0.09996706]
 [0.14642434]
 [0.04532084]
 [0.18698936]
 [0.19004757]
 [0.2147475

Predicted XOR output data based on trained weights: 
Expected (X1-X3): 
[0. 0. 1.]
Output (Y1): 
[0.104183]
Epoch # 660

Network Input : 
[[0. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 1.]
 [1. 0. 0.]
 [1. 0. 1.]
 [1. 1. 0.]
 [1. 1. 1.]]
Expected Output of XOR Gate Neural Network: 
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]]
Actual Output from XOR Gate Neural Network: 
[[0.32767106]
 [0.104183  ]
 [0.14089695]
 [0.04137683]
 [0.18440309]
 [0.18447751]
 [0.22109814]
 [0.78231111]]
Sum Squared Loss: 
0.08109419870989773


Predicted XOR output data based on trained weights: 
Expected (X1-X3): 
[0. 0. 1.]
Output (Y1): 
[0.10445613]
Epoch # 661

Network Input : 
[[0. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 1.]
 [1. 0. 0.]
 [1. 0. 1.]
 [1. 1. 0.]
 [1. 1. 1.]]
Expected Output of XOR Gate Neural Network: 
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]]
Actual Output from XOR Gate Neural Network: 
[[0.32859271]
 [0.10445613]
 [0.14057557]
 [0.04115113]
 [0.18424809]
 [0.18411493]
 [0.22146443

 [1. 1. 1.]]
Expected Output of XOR Gate Neural Network: 
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]]
Actual Output from XOR Gate Neural Network: 
[[0.34620268]
 [0.11005495]
 [0.13467439]
 [0.03701667]
 [0.18117556]
 [0.17680673]
 [0.22814497]
 [0.78583679]]
Sum Squared Loss: 
0.07763395822013257


Predicted XOR output data based on trained weights: 
Expected (X1-X3): 
[0. 0. 1.]
Output (Y1): 
[0.11036854]
Epoch # 681

Network Input : 
[[0. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 1.]
 [1. 0. 0.]
 [1. 0. 1.]
 [1. 1. 0.]
 [1. 1. 1.]]
Expected Output of XOR Gate Neural Network: 
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]]
Actual Output from XOR Gate Neural Network: 
[[0.34713817]
 [0.11036854]
 [0.13437785]
 [0.03680793]
 [0.18100516]
 [0.17640963]
 [0.22847752]
 [0.78597806]]
Sum Squared Loss: 
0.07746407620864101


Predicted XOR output data based on trained weights: 
Expected (X1-X3): 
[0. 0. 1.]
Output (Y1): 
[0.11068384]
Epoch # 682

Network Input : 
[[0. 0. 0.]
 [0. 0. 1.]


 [1. 1. 1.]]
Expected Output of XOR Gate Neural Network: 
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]]
Actual Output from XOR Gate Neural Network: 
[[0.36522038]
 [0.11665026]
 [0.1291105 ]
 [0.03303985]
 [0.17754677]
 [0.16894726]
 [0.23426117]
 [0.78792272]]
Sum Squared Loss: 
0.07427933820566382


Predicted XOR output data based on trained weights: 
Expected (X1-X3): 
[0. 0. 1.]
Output (Y1): 
[0.11699861]
Epoch # 701

Network Input : 
[[0. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 1.]
 [1. 0. 0.]
 [1. 0. 1.]
 [1. 1. 0.]
 [1. 1. 1.]]
Expected Output of XOR Gate Neural Network: 
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]]
Actual Output from XOR Gate Neural Network: 
[[0.36619296]
 [0.11699861]
 [0.12885511]
 [0.03285275]
 [0.17735208]
 [0.16856696]
 [0.23453212]
 [0.78798384]]
Sum Squared Loss: 
0.07411346674593239


Predicted XOR output data based on trained weights: 
Expected (X1-X3): 
[0. 0. 1.]
Output (Y1): 
[0.11734888]
Epoch # 702

Network Input : 
[[0. 0. 0.]
 [0. 0. 1.]


 [1. 1. 1.]]
Expected Output of XOR Gate Neural Network: 
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]]
Actual Output from XOR Gate Neural Network: 
[[0.38837513]
 [0.12521212]
 [0.12391102]
 [0.02905127]
 [0.17272685]
 [0.16085149]
 [0.23936905]
 [0.78820169]]
Sum Squared Loss: 
0.07047810111514108


Predicted XOR output data based on trained weights: 
Expected (X1-X3): 
[0. 0. 1.]
Output (Y1): 
[0.12561372]
Epoch # 724

Network Input : 
[[0. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 1.]
 [1. 0. 0.]
 [1. 0. 1.]
 [1. 1. 0.]
 [1. 1. 1.]]
Expected Output of XOR Gate Neural Network: 
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]]
Actual Output from XOR Gate Neural Network: 
[[0.38942576]
 [0.12561372]
 [0.12372011]
 [0.02889324]
 [0.17250109]
 [0.16053686]
 [0.23953076]
 [0.78815941]]
Sum Squared Loss: 
0.07031266644196552


Predicted XOR output data based on trained weights: 
Expected (X1-X3): 
[0. 0. 1.]
Output (Y1): 
[0.12601803]
Epoch # 725

Network Input : 
[[0. 0. 0.]
 [0. 0. 1.]


 [0.78699599]]
Sum Squared Loss: 
0.06781702215431126


Predicted XOR output data based on trained weights: 
Expected (X1-X3): 
[0. 0. 1.]
Output (Y1): 
[0.13241096]
Epoch # 740

Network Input : 
[[0. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 1.]
 [1. 0. 0.]
 [1. 0. 1.]
 [1. 1. 0.]
 [1. 1. 1.]]
Expected Output of XOR Gate Neural Network: 
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]]
Actual Output from XOR Gate Neural Network: 
[[0.406842  ]
 [0.13241096]
 [0.12112515]
 [0.02654043]
 [0.16870666]
 [0.15600566]
 [0.24131489]
 [0.7868849 ]]
Sum Squared Loss: 
0.067649424588377


Predicted XOR output data based on trained weights: 
Expected (X1-X3): 
[0. 0. 1.]
Output (Y1): 
[0.13285847]
Epoch # 741

Network Input : 
[[0. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 1.]
 [1. 0. 0.]
 [1. 0. 1.]
 [1. 1. 0.]
 [1. 1. 1.]]
Expected Output of XOR Gate Neural Network: 
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]]
Actual Output from XOR Gate Neural Network: 
[[0.40797022]
 [0.13285847]
 [0.12099321

Predicted XOR output data based on trained weights: 
Expected (X1-X3): 
[0. 0. 1.]
Output (Y1): 
[0.14602497]
Epoch # 769

Network Input : 
[[0. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 1.]
 [1. 0. 0.]
 [1. 0. 1.]
 [1. 1. 0.]
 [1. 1. 1.]]
Expected Output of XOR Gate Neural Network: 
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]]
Actual Output from XOR Gate Neural Network: 
[[0.44137307]
 [0.14602497]
 [0.11882361]
 [0.02304866]
 [0.16083562]
 [0.15010239]
 [0.24053579]
 [0.78239479]]
Sum Squared Loss: 
0.06270574324249417


Predicted XOR output data based on trained weights: 
Expected (X1-X3): 
[0. 0. 1.]
Output (Y1): 
[0.14649742]
Epoch # 770

Network Input : 
[[0. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 1.]
 [1. 0. 0.]
 [1. 0. 1.]
 [1. 1. 0.]
 [1. 1. 1.]]
Expected Output of XOR Gate Neural Network: 
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]]
Actual Output from XOR Gate Neural Network: 
[[0.44262045]
 [0.14649742]
 [0.11879847]
 [0.0229432 ]
 [0.16053549]
 [0.14994101]
 [0.240424

Predicted XOR output data based on trained weights: 
Expected (X1-X3): 
[0. 0. 1.]
Output (Y1): 
[0.15612509]
Epoch # 792

Network Input : 
[[0. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 1.]
 [1. 0. 0.]
 [1. 0. 1.]
 [1. 1. 0.]
 [1. 1. 1.]]
Expected Output of XOR Gate Neural Network: 
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]]
Actual Output from XOR Gate Neural Network: 
[[0.47049509]
 [0.15612509]
 [0.11892484]
 [0.02079352]
 [0.15330205]
 [0.14676065]
 [0.23699178]
 [0.77856896]]
Sum Squared Loss: 
0.058695374373551545


Predicted XOR output data based on trained weights: 
Expected (X1-X3): 
[0. 0. 1.]
Output (Y1): 
[0.1565109]
Epoch # 793

Network Input : 
[[0. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 1.]
 [1. 0. 0.]
 [1. 0. 1.]
 [1. 1. 0.]
 [1. 1. 1.]]
Expected Output of XOR Gate Neural Network: 
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]]
Actual Output from XOR Gate Neural Network: 
[[0.47176942]
 [0.1565109 ]
 [0.11895354]
 [0.02070147]
 [0.15294265]
 [0.14662648]
 [0.236800

Actual Output from XOR Gate Neural Network: 
[[0.4945874 ]
 [0.16236263]
 [0.11961405]
 [0.01906914]
 [0.14601465]
 [0.14427679]
 [0.23297816]
 [0.77654894]]
Sum Squared Loss: 
0.05535249332649912


Predicted XOR output data based on trained weights: 
Expected (X1-X3): 
[0. 0. 1.]
Output (Y1): 
[0.16262155]
Epoch # 812

Network Input : 
[[0. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 1.]
 [1. 0. 0.]
 [1. 0. 1.]
 [1. 1. 0.]
 [1. 1. 1.]]
Expected Output of XOR Gate Neural Network: 
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]]
Actual Output from XOR Gate Neural Network: 
[[0.49584616]
 [0.16262155]
 [0.11965491]
 [0.01897796]
 [0.14560534]
 [0.14414985]
 [0.23274489]
 [0.77648473]]
Sum Squared Loss: 
0.055175460401592546


Predicted XOR output data based on trained weights: 
Expected (X1-X3): 
[0. 0. 1.]
Output (Y1): 
[0.16287305]
Epoch # 813

Network Input : 
[[0. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 1.]
 [1. 0. 0.]
 [1. 0. 1.]
 [1. 1. 0.]
 [1. 1. 1.]]
Expected Output of XOR Gate Neura

Predicted XOR output data based on trained weights: 
Expected (X1-X3): 
[0. 0. 1.]
Output (Y1): 
[0.16638415]
Epoch # 835

Network Input : 
[[0. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 1.]
 [1. 0. 0.]
 [1. 0. 1.]
 [1. 1. 0.]
 [1. 1. 1.]]
Expected Output of XOR Gate Neural Network: 
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]]
Actual Output from XOR Gate Neural Network: 
[[0.52477615]
 [0.16638415]
 [0.12070646]
 [0.01673084]
 [0.13559765]
 [0.14147186]
 [0.22634023]
 [0.77649576]]
Sum Squared Loss: 
0.05099455270216199


Predicted XOR output data based on trained weights: 
Expected (X1-X3): 
[0. 0. 1.]
Output (Y1): 
[0.16644208]
Epoch # 836

Network Input : 
[[0. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 1.]
 [1. 0. 0.]
 [1. 0. 1.]
 [1. 1. 0.]
 [1. 1. 1.]]
Expected Output of XOR Gate Neural Network: 
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]]
Actual Output from XOR Gate Neural Network: 
[[0.52605194]
 [0.16644208]
 [0.12076476]
 [0.01662256]
 [0.13514159]
 [0.1413727 ]
 [0.225988

Predicted XOR output data based on trained weights: 
Expected (X1-X3): 
[0. 0. 1.]
Output (Y1): 
[0.16575871]
Epoch # 852

Network Input : 
[[0. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 1.]
 [1. 0. 0.]
 [1. 0. 1.]
 [1. 1. 0.]
 [1. 1. 1.]]
Expected Output of XOR Gate Neural Network: 
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]]
Actual Output from XOR Gate Neural Network: 
[[0.5473554 ]
 [0.16575871]
 [0.12218254]
 [0.01469953]
 [0.12779189]
 [0.14015695]
 [0.21848461]
 [0.77934225]]
Sum Squared Loss: 
0.04748848016233746


Predicted XOR output data based on trained weights: 
Expected (X1-X3): 
[0. 0. 1.]
Output (Y1): 
[0.16559313]
Epoch # 853

Network Input : 
[[0. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 1.]
 [1. 0. 0.]
 [1. 0. 1.]
 [1. 1. 0.]
 [1. 1. 1.]]
Expected Output of XOR Gate Neural Network: 
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]]
Actual Output from XOR Gate Neural Network: 
[[0.54877499]
 [0.16559313]
 [0.12231829]
 [0.0145662 ]
 [0.12733993]
 [0.14011051]
 [0.217845

0.042914823342321884


Predicted XOR output data based on trained weights: 
Expected (X1-X3): 
[0. 0. 1.]
Output (Y1): 
[0.15941183]
Epoch # 870

Network Input : 
[[0. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 1.]
 [1. 0. 0.]
 [1. 0. 1.]
 [1. 1. 0.]
 [1. 1. 1.]]
Expected Output of XOR Gate Neural Network: 
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]]
Actual Output from XOR Gate Neural Network: 
[[0.57596356]
 [0.15941183]
 [0.12621246]
 [0.01208969]
 [0.12044195]
 [0.14006182]
 [0.20147636]
 [0.78845417]]
Sum Squared Loss: 
0.0425953396679272


Predicted XOR output data based on trained weights: 
Expected (X1-X3): 
[0. 0. 1.]
Output (Y1): 
[0.15880574]
Epoch # 871

Network Input : 
[[0. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 1.]
 [1. 0. 0.]
 [1. 0. 1.]
 [1. 1. 0.]
 [1. 1. 1.]]
Expected Output of XOR Gate Neural Network: 
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]]
Actual Output from XOR Gate Neural Network: 
[[0.57778972]
 [0.15880574]
 [0.12655557]
 [0.01193568]
 [0.12011206]
 [

 [0.80343668]]
Sum Squared Loss: 
0.03722597903857142


Predicted XOR output data based on trained weights: 
Expected (X1-X3): 
[0. 0. 1.]
Output (Y1): 
[0.14607492]
Epoch # 886

Network Input : 
[[0. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 1.]
 [1. 0. 0.]
 [1. 0. 1.]
 [1. 1. 0.]
 [1. 1. 1.]]
Expected Output of XOR Gate Neural Network: 
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]]
Actual Output from XOR Gate Neural Network: 
[[0.60820134]
 [0.14607492]
 [0.13290801]
 [0.0096616 ]
 [0.11663898]
 [0.14100181]
 [0.17468427]
 [0.80461608]]
Sum Squared Loss: 
0.036847198880998494


Predicted XOR output data based on trained weights: 
Expected (X1-X3): 
[0. 0. 1.]
Output (Y1): 
[0.14501692]
Epoch # 887

Network Input : 
[[0. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 1.]
 [1. 0. 0.]
 [1. 0. 1.]
 [1. 1. 0.]
 [1. 1. 1.]]
Expected Output of XOR Gate Neural Network: 
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]]
Actual Output from XOR Gate Neural Network: 
[[0.61036712]
 [0.14501692]
 [0.13335

 [1.]]
Actual Output from XOR Gate Neural Network: 
[[0.64832755]
 [0.12472899]
 [0.1387676 ]
 [0.00721717]
 [0.11462527]
 [0.14029197]
 [0.1407423 ]
 [0.82678063]]
Sum Squared Loss: 
0.030146687647228138


Predicted XOR output data based on trained weights: 
Expected (X1-X3): 
[0. 0. 1.]
Output (Y1): 
[0.12363894]
Epoch # 906

Network Input : 
[[0. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 1.]
 [1. 0. 0.]
 [1. 0. 1.]
 [1. 1. 0.]
 [1. 1. 1.]]
Expected Output of XOR Gate Neural Network: 
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]]
Actual Output from XOR Gate Neural Network: 
[[0.65028433]
 [0.12363894]
 [0.13885195]
 [0.00710718]
 [0.11451686]
 [0.14014638]
 [0.13921704]
 [0.8278357 ]]
Sum Squared Loss: 
0.029836882793329935


Predicted XOR output data based on trained weights: 
Expected (X1-X3): 
[0. 0. 1.]
Output (Y1): 
[0.1225608]
Epoch # 907

Network Input : 
[[0. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 1.]
 [1. 0. 0.]
 [1. 0. 1.]
 [1. 1. 0.]
 [1. 1. 1.]]
Expected Output of XOR Gat

 [0.84180429]]
Sum Squared Loss: 
0.025729466662529277


Predicted XOR output data based on trained weights: 
Expected (X1-X3): 
[0. 0. 1.]
Output (Y1): 
[0.10807661]
Epoch # 922

Network Input : 
[[0. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 1.]
 [1. 0. 0.]
 [1. 0. 1.]
 [1. 1. 0.]
 [1. 1. 1.]]
Expected Output of XOR Gate Neural Network: 
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]]
Actual Output from XOR Gate Neural Network: 
[[0.67874793]
 [0.10807661]
 [0.13703898]
 [0.00559862]
 [0.11227602]
 [0.13661415]
 [0.11904207]
 [0.8426212 ]]
Sum Squared Loss: 
0.025487863484273936


Predicted XOR output data based on trained weights: 
Expected (X1-X3): 
[0. 0. 1.]
Output (Y1): 
[0.10722808]
Epoch # 923

Network Input : 
[[0. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 1.]
 [1. 0. 0.]
 [1. 0. 1.]
 [1. 1. 0.]
 [1. 1. 1.]]
Expected Output of XOR Gate Neural Network: 
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]]
Actual Output from XOR Gate Neural Network: 
[[0.68036154]
 [0.10722808]
 [0.1367

Predicted XOR output data based on trained weights: 
Expected (X1-X3): 
[0. 0. 1.]
Output (Y1): 
[0.09414819]
Epoch # 941

Network Input : 
[[0. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 1.]
 [1. 0. 0.]
 [1. 0. 1.]
 [1. 1. 0.]
 [1. 1. 1.]]
Expected Output of XOR Gate Neural Network: 
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]]
Actual Output from XOR Gate Neural Network: 
[[0.70679372]
 [0.09414819]
 [0.12956482]
 [0.00433496]
 [0.10852766]
 [0.13068313]
 [0.10309641]
 [0.85606778]]
Sum Squared Loss: 
0.021480165771295093


Predicted XOR output data based on trained weights: 
Expected (X1-X3): 
[0. 0. 1.]
Output (Y1): 
[0.09352802]
Epoch # 942

Network Input : 
[[0. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 1.]
 [1. 0. 0.]
 [1. 0. 1.]
 [1. 1. 0.]
 [1. 1. 1.]]
Expected Output of XOR Gate Neural Network: 
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]]
Actual Output from XOR Gate Neural Network: 
[[0.7081375 ]
 [0.09352802]
 [0.12907866]
 [0.00428127]
 [0.10830785]
 [0.13034623]
 [0.10242

 [0.86764621]]
Sum Squared Loss: 
0.018013756503904032


Predicted XOR output data based on trained weights: 
Expected (X1-X3): 
[0. 0. 1.]
Output (Y1): 
[0.08242457]
Epoch # 963

Network Input : 
[[0. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 1.]
 [1. 0. 0.]
 [1. 0. 1.]
 [1. 1. 0.]
 [1. 1. 1.]]
Expected Output of XOR Gate Neural Network: 
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]]
Actual Output from XOR Gate Neural Network: 
[[0.73404168]
 [0.08242457]
 [0.11782444]
 [0.0033767 ]
 [0.10340346]
 [0.12308662]
 [0.09105766]
 [0.86813616]]
Sum Squared Loss: 
0.017867975001664753


Predicted XOR output data based on trained weights: 
Expected (X1-X3): 
[0. 0. 1.]
Output (Y1): 
[0.08197273]
Epoch # 964

Network Input : 
[[0. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 1.]
 [1. 0. 0.]
 [1. 0. 1.]
 [1. 1. 0.]
 [1. 1. 1.]]
Expected Output of XOR Gate Neural Network: 
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]]
Actual Output from XOR Gate Neural Network: 
[[0.7351781 ]
 [0.08197273]
 [0.1172

0.015251431231864558


Predicted XOR output data based on trained weights: 
Expected (X1-X3): 
[0. 0. 1.]
Output (Y1): 
[0.07402392]
Epoch # 984

Network Input : 
[[0. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 1.]
 [1. 0. 0.]
 [1. 0. 1.]
 [1. 1. 0.]
 [1. 1. 1.]]
Expected Output of XOR Gate Neural Network: 
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]]
Actual Output from XOR Gate Neural Network: 
[[0.75635619]
 [0.07402392]
 [0.10582304]
 [0.00278665]
 [0.09824468]
 [0.11585843]
 [0.08326649]
 [0.8774544 ]]
Sum Squared Loss: 
0.01513425665247922


Predicted XOR output data based on trained weights: 
Expected (X1-X3): 
[0. 0. 1.]
Output (Y1): 
[0.07367356]
Epoch # 985

Network Input : 
[[0. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 1.]
 [1. 0. 0.]
 [1. 0. 1.]
 [1. 1. 0.]
 [1. 1. 1.]]
Expected Output of XOR Gate Neural Network: 
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]]
Actual Output from XOR Gate Neural Network: 
[[0.75734275]
 [0.07367356]
 [0.1052555 ]
 [0.00276421]
 [0.09799795]
 